import Link from "next/link";
import Image from "next/image";

import { Geist, Geist_Mono } from "next/font/google";
import { Quicksand } from "next/font/google";
import { Barlow } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

export const metadata = {
  title: "Statistical Sampling",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col gap-1`}>
        <nav className={"w-full flex flex-row justify-end gap-10 text-sm"}>
          <Link href={"/"} className={"hover:underline"}>Home</Link>
          <Link href={"/sampling"} className={"hover:underline"}>Sampling</Link>
          <Link href={"/info"} className={"hover:underline"}>Info</Link>
        </nav>
        <header className={`w-full h-250px bg-[url(./banner.jpg)] p-10`}>
          <h1 className={`${quicksand.variable} w-fit mt-10 text-4xl italic`} style={{ textShadow: "var(--outline)" }}>Statistical Sampling</h1>
        </header>
        <main className={"h-100 p-2"}>
          {children}
        </main>
      </body>
    </html>
  );
}
